name             "ace-haproxy"
maintainer       "Ace of Sales"
maintainer_email "cookbooks@aceofsales.com"
license          "Apache 2.0"
description      "Configures haproxy for aceofsales"
version          "1.0.0"
